baseline: &defaults
  env: {}
  import_ddtrace: false
  import_ddtrace_auto: false
  import_flask: false
  import_django: false
baseline_flask:
  <<: *defaults
  import_flask: true
baseline_django:
  <<: *defaults
  import_django: true
import_ddtrace:
  <<: *defaults
  import_ddtrace: true
import_ddtrace_flask:
  <<: *defaults
  import_ddtrace: true
  import_flask: true
import_ddtrace_django:
  <<: *defaults
  import_ddtrace: true
  import_django: true
import_ddtrace_auto:
  <<: *defaults
  import_ddtrace_auto: true
import_ddtrace_auto_flask:
  <<: *defaults
  import_ddtrace_auto: true
  import_flask: true
import_ddtrace_auto_django:
  <<: *defaults
  import_ddtrace_auto: true
  import_django: true
import_ddtrace_auto_start_telemetry:
  <<: *defaults
  # By default telemetry collection is enabled after 10 seconds we need to force it to start immediately
  # to detect the overhead.
  env: {"_DD_INSTRUMENTATION_TELEMETRY_TESTS_FORCE_APP_STARTED": "true"}
  import_ddtrace_auto: true
